version: "3"

services:
  flask-app:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: python3 app.py

  react-app:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - flask-app
    command: npm start
