---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "recsysexp"
  namespace: "default"
  labels:
    app: "recsysexp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "recsysexp"
  template:
    metadata:
      labels:
        app: "recsysexp"
    spec:
      containers:
        - name: "frontend"
          image: "front_recsysexp:latest"
          imagePullPolicy: "Never"
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 512Mi
              cpu: "1"
          ports:
            - containerPort: 3000
        - name: "task-executor"
          image: "task-executor:latest"
          imagePullPolicy: "Never"
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 512Mi
              cpu: "1"
          ports:
            - containerPort: 5050
        - name: "recsysexp"
          image: "sansilva/recsysexp:latest"
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 512Mi
              cpu: "1"
          ports:
            - containerPort: 5000
